[package]
name = "shoddy-raid"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
rusqlite = { version = "0.32", features = ["bundled"] }
anyhow = "1.0"
blake3 = "1.5"
hex = "0.4"
vdisk = { path = "../vdisk" }

[target.'cfg(target_os = "linux")'.dependencies]
udev = "0.9"

[target.'cfg(target_os = "windows")'.dependencies]
windows-sys = { version = "0.52", features = [
    "Win32_Foundation",
    "Win32_System_IO",
    "Win32_System_Ioctl",
    "Win32_Storage_FileSystem",
    "Win32_Security"
] }

